spring.application.name=www-programming

# Server port
server.port=8081

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DB_PinkyCloud;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=sapassword
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Security Default Dev Account
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

spring.jpa.properties.hibernate.use_nationalized_character_data=true
spring.jpa.properties.hibernate.format_sql=false

# Encoding
spring.messages.encoding=UTF-8

# Thymeleaf
spring.thymeleaf.cache=false