name: Backend CI

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cấp quyền thực thi cho Maven Wrapper
        run: chmod +x mvnw

      - name: Build và Test với Maven
        run: ./mvnw clean verify